import type { Metadata } from "next";
import { Geist, Geist_Mono, Barlow } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/components/shared/ScrollToTop";
import { AppContextProvider } from "@/context/AppContext";


const balow = Barlow({
  weight: ["100", "200", "300", "400", "500"],
  subsets: ["latin"],
  variable: "--font-barlow-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body className={`${balow.className} antialiased`}>
          <ScrollToTop />

          {children}
        </body>
      </AppContextProvider>
    </html>
  );
}
